version: "3.8"
services:
  client:
    build:
      context: ../Adopt-your-bestie/client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=development
      - PORT=3000
    depends_on:
      - server
  server:
    build:
      context: ../Adopt-your-bestie/server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
