export const pets = [
  {
    name: "Rascal",
    petType: "dog",
    breed: "Pug",
    gender: "Male",
    age: "6 months",
    icon: "/images/pets/rascal.jpg",
    description: "A playful Pug with a curious nature.",
  },
  {
    name: "Bandit",
    petType: "dog",
    breed: "French Bull Dog",
    gender: "Male",
    age: "6 months",
    icon: "/images/pets/bandit.jpg",
    description: "A French Bull Dog with a lot of energy.",
  },
  {
    name: "Fin",
    petType: "dog",
    breed: "Weiner Dog",
    gender: "Male",
    age: "6 months",
    icon: "/images/pets/fin.jpg",
    description: "A friendly Weiner Dog with a gentle temperament.",
  },
  {
    name: "Luna",
    petType: "cat",
    breed: "Persian Cat",
    gender: "Female",
    age: "1 year",
    icon: "/images/pets/luna.jpg",
    description: "A Persian cat with a calm demeanor.",
  },
  {
    name: "Whiskers",
    petType: "cat",
    breed: "Siamese Cat",
    gender: "Male",
    age: "2 years",
    icon: "/images/pets/whiskers.jpg",
    description: "A Siamese cat with striking blue eyes and a curious nature.",
  },
  {
    name: "Polly",
    petType: "bird",
    breed: "Parrot",
    gender: "Female",
    age: "2 years",
    icon: "/images/pets/polly.jpg",
    description: "A colorful parrot with a vibrant personality.",
  },
  {
    name: "Thumper",
    petType: "rabbit",
    breed: "Holland Lop",
    gender: "Male",
    age: "1 year",
    icon: "/images/pets/thumper.jpg",
    description: "A gentle Holland Lop rabbit with floppy ears.",
  },
  {
    name: "Coco",
    petType: "hamster",
    breed: "Syrian Hamster",
    gender: "Female",
    age: "1 year",
    icon: "/images/pets/coco.jpg",
    description: "A Syrian Hamster with a playful demeanor.",
  },
];

export const petTypes = ["", "Dog", "Cat", "Rabbit", "Hamster", "Bird"];
